### ISSUE TITLE
typescript issues

### ISSUE THREAD

**Issue by nityanantan23** [tensoremr/web-client#1]
a lot of typescript issues, how do i solve this?

![image](https://user-images.githubusercontent.com/48348087/173850461-609ee7aa-73fa-4dd1-90a5-6074c37885bc.png)

**Comment by kidus-tiliksew** [comment]
Go into _packages/components_ then run _yarn build_. Do that for all the other packages (api, models etc). Finally go into the root of the folder and run _yarn_ 

There will be a better solution to this soon

**Comment by nityanantan23** [comment]
lemme try

**Comment by kidus-tiliksew** [comment]
You can pull the latest version which solves the problem. Run `yarn` then `lerna run build` and finally `yarn start`

**Comment by nityanantan23** [comment]
the web app works now, but for the go server in another repo...it doesn't support windows due to using grep

**Comment by kidus-tiliksew** [comment]
The Makefile? You can just use `go run main.go` to run the program. Make sure you pull the latest version. 

Admin user is `info@tensorsystems.net` and password is `changeme`.

I am working on documentation

**Comment by nityanantan23** [comment]
for the server error, i have open issue in here
https://github.com/tensoremr/server/issues/2#issue-1306711329
